spring.application.name: ecom-gateway-server
server.port: 9000
zuul.ribbon.eager-load.enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
server.port: 9000
spring:
  profiles: container
  application.name: ecom-gateway-server
  cloud.config.uri: "http://ecom-configuration-server:8888"
eureka.client.serviceUrl.defaultZone: "http://ecom-discovery-server:8761/eureka"  

management.endpoints.web.exposure.include: "*"

zuul.ribbon.eager-load.enabled: true
