spring.application.name: ecom-admin-server
server.port: 8181
eureka:   
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 5  
    serviceUrl.defaultZone: "http://localhost:8761/eureka"  
zuul.ribbon.eager-load.enabled: true      

---

server.port: 8181

spring:
  profiles: container
  application.name: ecom-admin-server
  cloud.config.uri: "http://ecom-configuration-server:8888"
  boot.admin.discovery.ignored-services: spring-boot-admin  

eureka.client.serviceUrl.defaultZone: "http://ecom-discovery-server:8761/eureka"      
