spring.application.name: ecom-product-service
server.port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
axon:
  amqp:
    exchange: ecom-axon3-exchange
    queue: ecom-core-queue
    eventhandling.processors.ECOM_CORE_EVENT_PROCESSOR.source: ecomCoreEventQueue  
    
    

ecom.product.img.location: c://devel/home/juancpe/devel/juancpaz/ecom/ecom-fs/productImg

---

server.port: 8081

spring:
  profiles: container
  application.name: ecom-product-service
  cloud.config.uri: "http://ecom-configuration-server:8888"
  rabbitmq.host: ecom-rabbit1
  data.mongodb.host: ecom-mongodb
  
eureka.client.serviceUrl.defaultZone: "http://ecom-discovery-server:8761/eureka"  
zuul.ribbon.eager-load.enabled: true      

axon:
  amqp:
    exchange: ecom-axon3-exchange
    queue: ecom-core-queue
    eventhandling.processors.ECOM_CORE_EVENT_PROCESSOR.source: ecomCoreEventQueue  

ecom.product.img.location: c://devel/home/juancpe/devel/juancpaz/ecom/ecom-fs/productImg
