spring.application.name: ecom-product-service
server.port: 8081

axon:
  amqp:
    exchange: ecom-axon3-exchange
    queue: ecom-core-queue
    eventhandling.processors.ECOM_CORE_EVENT_PROCESSOR.source: ecomCoreEventQueue  

ecom.product.img.location: c://devel/home/juancpe/devel/juancpaz/ecom/ecom-fs/productImg

---

server.port: 8081

spring:
  profiles: container
  application.name: ecom-product-service
  cloud.config.uri: "http://ecom-configuration-server:8888"
  rabbitmq.host: ecom-rabbit1
  data.mongodb.host: ecom-mongodb
  
eureka:
  instance:
    hostname: ecom-discovery-server
    port: 8761
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/  

axon:
  amqp:
    exchange: ecom-axon3-exchange
    queue: ecom-core-queue
    eventhandling.processors.ECOM_CORE_EVENT_PROCESSOR.source: ecomCoreEventQueue  

ecom.product.img.location: c://devel/home/juancpe/devel/juancpaz/ecom/ecom-fs/productImg
